// <auto-generated />
namespace MVCBlogDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-alpha1-21218")]
    public sealed partial class tags1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tags1));
        
        string IMigrationMetadata.Id
        {
            get { return "201508300045373_tags1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
